### ISSUE TITLE
Make testdata.csv available

### ISSUE THREAD

**Issue by frallain** [mverleg/array_storage_benchmark#5]
Hi, 
I am trying to reproduce your benchmark, I could install all the dependencies but it now asks for `testdata.csv`. Could you please provide it? Thanks in advance.

**Comment by mverleg** [comment]
I might have lost that... I think I'll make it optional. You could even use a representative dataset to benchmark for your own application.

**Comment by mverleg** [comment]
I added the data back after all. It's still easy to replace it by more realistic data though.
