### ISSUE TITLE
Add protobuf

### ISSUE THREAD

**Issue by darwinyip** [mverleg/array_storage_benchmark#7]

**Comment by mverleg** [comment]
Is protobuf used as a storage format? I might add it though, do you have a protobuf implementation to recommend? Google said numproto...

**Comment by mverleg** [comment]
I looked at numproto, it seems to store an array of bytes in a protobuf message. The array of bytes is just the result of numpy.save (without pickle). It doesn't, for example, store metadata in protobuf fields.

**Comment by mverleg** [comment]
Also looked at numpy-protobuf, which has a nice protobuf format, but doesn't seem to include much code (or documentation) beyond the protobuf format description.

**Comment by mverleg** [comment]
I'm going to close this as I can't find a promising enough implementation. If there's a promising library that people use, then I might add a benchmark for it. Feel free to open this issue with a link to such a library.
